# Generated by Django 2.1 on 2018-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0002_auto_20181124_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='trend',
            field=models.IntegerField(blank=True, default=1, verbose_name='趋势'),
        ),
    ]
