# Generated by Django 2.1.3 on 2018-11-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0003_teams_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='times',
            field=models.IntegerField(default=0, verbose_name='第几次更新'),
        ),
    ]
